DROP TABLE IF EXISTS GROUPS_MESSAGES;
DROP TABLE IF EXISTS MESSAGES;
DROP TABLE IF EXISTS USERS_GROUPS;
DROP TABLE IF EXISTS INVITATIONS;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS GROUPS;
DROP TABLE IF EXISTS EVENTS;
DROP TABLE IF EXISTS ENTITIES;