CREATE TABLE USERS (ID SERIAL PRIMARY KEY, USERNAME VARCHAR(30) NOT NULL, PASSWORD VARCHAR(30) NOT NULL);
CREATE TABLE EVENTS (ID SERIAL PRIMARY KEY, NAME VARCHAR(255) NOT NULL, EVENT_START DATE NOT NULL, LOCATION VARCHAR(255) NOT NULL);
CREATE TABLE GROUPS (ID SERIAL PRIMARY KEY, NAME VARCHAR(255) NOT NULL);
CREATE TABLE USERS_GROUPS (USER_ID BIGINT NOT NULL, GROUP_ID BIGINT NOT NULL, FOREIGN KEY(USER_ID) REFERENCES USERS(ID), FOREIGN KEY(GROUP_ID) REFERENCES GROUPS(ID), PRIMARY KEY(USER_ID, GROUP_ID));
CREATE TABLE INVITATIONS (USER_ID BIGINT NOT NULL, EVENT_ID BIGINT NOT NULL, FOREIGN KEY(USER_ID) REFERENCES USERS(ID), FOREIGN KEY(EVENT_ID) REFERENCES EVENTS(ID),PRIMARY KEY(USER_ID, EVENT_ID));